# /.github/workflows/deploy.yml
name: Blog Deploy
on:
  repository_dispatch:
    types: [blog_update, category_update]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - run: npm install
      - run: npm run build
      - run: npm run deploy
